### ISSUE TITLE
Missing: Testing Routine without Ground Truth

### ISSUE THREAD

**Issue by stalhabukhari** [luozhengrong/HDC-Net#1]
Hi!

Thank you for making the source code of your work available. I noticed that the testing routine does not work without Ground Truth segmentations due to issue in `BraTSDataset` class of `data/datasets.py` (even with `mode=2`). I can proceed to make changes in the code to enable it, but I wanted to have your version of the code to reproduce the results in the paper.

Best Regards,
Talha

**Comment by luozhengrong** [comment]
Hi|

If you run preprocess.py, the nib_load function will return the constant value for nonexistent path, we use constant values instead of Ground Truth segmentations. Thank you for your mail.

Best Regards,
Zhengrong Luo

**Comment by stalhabukhari** [comment]
@luozhengrong
Alright! I missed the pre-processing step as it was also generating an error and I thought it was mistakenly trying to read a missing label volume, therefore I replaced the label with `None`. Thank you for the clarification!
